### ISSUE TITLE
ESP library

### ISSUE THREAD

**Issue by Danielpur-1** [khoih-prog/Blynk_Teensy#1]
Hi, 
I have tried running the sample code you attached. Unfortunatelly, i cant find the library ESP8266_Lib.h.
Can you please add a link to download the library?

**Comment by khoih-prog** [comment]
As the library's name [**Blynk_Teensy**](https://github.com/khoih-prog/Blynk_Teensy) implies, you first have to install Blynk successfully to use the library.

To install, download latest stable  [**Blynk Releases v0.6.1**](https://github.com/blynkkk/blynk-library/releases/tag/v0.6.1), then follow the instruction [**How to install Blynk Library for Arduino IDE**](http://help.blynk.cc/en/articles/512105-how-to-install-blynk-library-for-arduino-ide).

If you'd have any more issue of installation, it's better to post question to get help on [**Blynk Community**](https://community.blynk.cc/)

---

#### Notes:

To install manually if follow instructions but unsuccessful

1. Download the [Blynk_Release_v0.6.1.zip](https://github.com/blynkkk/blynk-library/releases/tag/v0.6.1)
2. Unzip => 

* libraries
  * Blynk
  * BlynkESP8266_Lib
  * Time
  * TinyGSM
* tools

Then copy all into your Arduino Library's folder
